# Generated by Django 4.0.4 on 2022-05-30 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colab',
            fields=[
                ('productoid', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID del producto')),
                ('nombre', models.CharField(max_length=50, verbose_name='nombre producto')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='usuario')),
                ('descripcion', models.CharField(max_length=50, verbose_name='descripcion')),
            ],
        ),
    ]
