# Generated by Django 4.0.4 on 2022-06-25 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('rut', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Nombre de usuario')),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre del empleado')),
                ('apellido', models.CharField(max_length=100, verbose_name='Nombre')),
                ('email', models.CharField(max_length=100, verbose_name='apellido')),
                ('telefono', models.IntegerField(verbose_name='numero de telefono')),
                ('cargo', models.CharField(max_length=100, verbose_name='Cargo')),
            ],
        ),
    ]
