# Generated by Django 3.2.3 on 2022-06-28 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleados',
            name='sueldo',
            field=models.CharField(max_length=10, null=True, verbose_name='sueldo'),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='apellido',
            field=models.CharField(max_length=100, verbose_name='apellido'),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='email',
            field=models.CharField(max_length=100, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='rut',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='rut'),
        ),
    ]
